services:
  newton:
    image: thenewtoncapstone/newton:l4t-r36.4.0
    container_name: newton
    volumes:
      - "${PWD}:/home/newton"
    restart: unless-stopped
    stdin_open: true
    tty: true
