services:
  newton:
    image: thenewtoncapstone/newton:l4t-r36.4.0
    container_name: newton
    network_mode: "host"
    volumes:
      - "${PWD}:/home/newton"
    restart: unless-stopped
    stdin_open: true # docker run -i
    tty: true # docker run -t
