name: "Run TODO to Issue"

on:
  push:
    branches:
      - '**'  # This will trigger on all branches
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      MANUAL_COMMIT_REF:
        description: "The SHA of the commit to get the diff for"
        required: true
      MANUAL_BASE_REF:
        description: "By default, the commit entered above is compared to the one directly before it; to go back further, enter an earlier SHA here"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      issues: write  # Required to create issues
      contents: read  # Required to read repository contents
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches
      
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v5"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          CLOSE_ISSUES: false
          AUTO_ASSIGN: true
          IGNORE_PATHS: |
            node_modules/
            .git/
            dist/
            build/
          TODO_PATTERN: "(?:TODO|FIXME|BUG|HACK):.+"  # Matches TODO:, FIXME:, BUG:, HACK:
          LABEL_NAME: "todo"
          LABEL_COLOR: "ff0000"  # Red color for visibility
